### ISSUE TITLE
Add forward translation of Photovoltaics

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-openstudio-gem#182]
This can only be completed after these issues are addressed:

https://github.com/ladybug-tools/honeybee-schema/issues/289
https://github.com/ladybug-tools/honeybee-energy/issues/529

**Comment by tanushree04** [comment]
@chriswmackey I would be happy to take up the forward/reverse translation of PV systems once you are able to add them to the schema

**Comment by chriswmackey** [comment]
I forgot to close out this issue as it has been addressed via https://github.com/ladybug-tools/honeybee-openstudio-gem/pull/327
