### ISSUE TITLE
Honeybee version 2.34.4 installation error

### ISSUE THREAD

**Issue by Nasia-A** [ladybug-tools/honeybee-openstudio-gem#313]
Hi, I used to run UrbanOpt with Honeybee and Dragonfly through Rhino-Grasshopper, and my energy model used to give me results (the default reports folder) but after the updated release does not give me results due to dependency issues. I have tried to install the new Honeybee 2.34.4 release and I get error to the second step which is about the openstudio installation. The error is:

**gem install openstudio-extension
Successfully installed openstudio-extension-0.6.0
Parsing documentation for openstudio-extension-0.6.0
unable to convert "\xB0" from ASCII-8BIT to UTF-8 for lib/files/openstudio-extension-gem-test.ddy, skipping
Done installing documentation for openstudio-extension after 1 seconds
1 gem installed**

I ignored that and I run the 3rd step which is about executing rake file, but then I got that error:

**C:\Users\******\honeybee-openstudio-gem>bundle exec rake
rake aborted!
LoadError: cannot load such file -- openstudio
C:/Users/******/honeybee-openstudio-gem/Rakefile:10:in `require'
C:/Users/******/honeybee-openstudio-gem/Rakefile:10:in `<top (required)>'
(See full trace by running task with --trace)**

Do you have any idea for solving it? Any help would be totally appreciated!
Thanking you in advance.
Nasia

**Comment by chriswmackey** [comment]
Hi @Nasia-A ,

Really sorry that I missed this several months ago. It was an internal issue with URBANopt's dependency tree that broke all URBANopt simulations (not just the ones using honeybee-openstudio-gem). The team at NREL fixed it and we put in a safeguard to make sure that this never happens again with this PR:

https://github.com/ladybug-tools/honeybee-openstudio-gem/pull/315
