### ISSUE TITLE
Get the measure to accept Face3Ds with holes

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-openstudio-gem#47]
We say that we support this in the schema but we don't have code in the measure to translate from the face with the hole to the format the EnergyPlus and OpenStudio accept, which is only a single list of points that turns inward to cut out the holes:

Here are the parts of my code that do this on the Python end:
[This part checks the input recureively loops through holes](https://github.com/ladybug-tools/ladybug-geometry/blob/master/ladybug_geometry/geometry2d/polygon.py#L210-L218)
[This part is doing the heavy lifting of the calculation](https://github.com/ladybug-tools/ladybug-geometry/blob/master/ladybug_geometry/geometry2d/polygon.py#L783-L799)
[And here is where we calculate the distance between two points](https://github.com/ladybug-tools/ladybug-geometry/blob/master/ladybug_geometry/geometry3d/pointvector.py#L409-L412)

We'll have to translate this to Ruby to integrate it into the measure.

**Comment by chriswmackey** [comment]
I also wanted to note that we can take care of the triangulation of sub-faces on the Python end before we export the Model to the JSON. So we only have to worry about supporting holes on Faces and Shades right now.

**Comment by chriswmackey** [comment]
I'm removing the critical tag for now since I have a workaround implemented on the Python end for the time being.

**Comment by chriswmackey** [comment]
This has been addressed.

**Comment by agonzalezesteve** [comment]
@chriswmackey how this has been faced?
